### PR TITLE
Refactored how complex eigenvalues are managed

### PR DESCRIPTION
**Pull request by pablosanjose**
Hamiltonians are hermitian more often than not, but we don't enforce hermiticity anywhere. However, one place it is crucial is when computing bandstructures. To signal real eigenvalues we use the `similarmatrix(h)` mechanism when calling `bloch!`. By making it `Hermitian`, all diagonalizers know that they must return real eigenvalues. This PR makes `bandstructure` always call `bandstructure!(matrix, h,...)` with `matrix = Hermitian(similarmatrix(h))`, so that by default hermiticity is enforced in bandstructure calculations.

### CODE REVIEW

**Comment by BacAmorim** [comment]
Notice that Arpack does not take advantage in any way of the Hermitian nature of a Hamiltonian. If `spMat` is a complex sparse matrix, the eigenvalues return by `eigs` will be complex, regardless of whether `spMat` is hermitian or not, even if one forces Hermiticity with `Hermitian(spMat)`.  

To check this:
```julia
using SparseArrays, LinearAlgebra, Arpack, BenchmarkTools

# a function that generates a random sparse Hermitian matrix
function randhermitian(m, density)
    nnzvals = floor(Int, m*m*density/2)
    I, J, V  = Int[], Int[], Complex{Float64}[]
    for n=1:nnzvals
        i, j, v =  rand(1:m), rand(1:m), rand() + 1im*rand()
        push!(I, i)
        push!(J, j)
        push!(V, v)
        push!(I, j)
        push!(J, i)
        push!(V, conj(v))
    end
    return sparse(I, J, V)
end

spMat = randhermitian(100, 0.1)
sphermMat = Hermitian(mat)
;
```

Both matrices are recognized as being Hermitian
```julia
ishermitian(spMat), ishermitian(sphermMat)
```
returns:
```julia
(true, true)
```

`eigs` assumes that the eigenvalues of both matrices are complex:
```julia
@btime eigs($spMat)
```
returns
```julia
  2.726 ms (458 allocations: 87.05 KiB)
(Complex{Float64}[6.38679-3.86661e-18im, -5.26097-6.36005e-17im, 5.2317+1.68884e-16im, -4.96372-3.94821e-17im, 4.79452-3.20117e-17im, -4.57886-3.89298e-17im], Complex{Float64}[-0.0235875+0.0375271im 0.0191232-0.0822919im … -0.046088+0.0352338im 0.092358+0.00842964im; -0.0383234+0.0245745im 0.00736794-0.00125036im … 0.0809299-0.047027im -0.0197786-0.0666463im; … ; -0.00861495+0.0047017im -0.00787599+0.00767803im … 0.0161022-0.00917563im -0.0164308+0.0107445im; -0.0736275-0.00792689im -0.000217106+0.0168567im … 0.0418204-0.0935973im -0.00532962-0.0503973im], 6, 8, 105, Complex{Float64}[-0.104123+0.446877im, -0.00237251+0.00651867im, 0.00306145+0.0128138im, 0.206308-0.115088im, 0.025549+0.166776im, 0.0605001+0.0984284im, -0.155832-0.102242im, 0.304917+0.0285006im, -0.109321+0.00834234im, 0.11217+0.0142534im  …  -0.105343+0.115026im, 0.136068-0.0288424im, -0.00687813+0.0638936im, -0.105005+0.0900243im, -0.0271191+0.125624im, 0.059191+0.0141579im, -0.142874-0.198955im, 0.0293441-0.00546772im, 0.166739+0.0830108im, 0.184608+0.134268im])
```
and 
```julia
@btime eigs($sphermMat)
```
returns
```julia
  22.357 ms (458 allocations: 87.05 KiB)
(Complex{Float64}[6.38679-4.10137e-17im, -5.26097+2.31852e-17im, 5.2317-1.07364e-16im, -4.96372+7.81894e-17im, 4.79452-1.03227e-17im, -4.57886-5.68695e-17im], Complex{Float64}[0.0244091+0.036998im -0.00780508+0.0841233im … -0.00406104-0.0578709im 0.0916579+0.0141387im; 0.00652105+0.0450562im -0.0071308+0.00223644im … -0.00526292+0.0934531im -0.0156092-0.0677442im; … ; 0.000717022+0.00978822im 0.00676389-0.00867371im … -0.00119835+0.0184943im -0.0170653+0.00970525im; -0.0376729+0.0637542im -0.00206723-0.0167308im … 0.0551432+0.0864212im -0.00219524-0.0506308im], 6, 8, 106, Complex{Float64}[0.0847605-0.156267im, -0.283474-0.0375631im, -0.13569-0.0462436im, -0.129908+0.0738018im, -0.207422-0.078947im, -0.0921288-0.101276im, 0.247395+0.159433im, -0.0426459+0.0277813im, 0.126764-0.13826im, 0.111859-0.160762im  …  0.266996+0.0914815im, 0.147137+0.148407im, -0.0792815+0.199975im, 0.0283809+0.0886215im, 0.0911383-0.0666421im, 0.0315797+0.0652587im, 0.158394+0.110572im, 0.339634-0.393847im, 0.0914225+0.0191909im, 0.030372+0.283148im])
```
Furthermore, passing a `Hermitian()` view might even slow performance of `eigs`.

**Comment by pablosanjose** [comment]
Thanks for the feedback @BacAmorim! It's rather strange, for me the `Hermitian` overhead is minimal. I'm running both 1.3 and master, and Arpack is on version 0.4.0
```
julia> @btime eigs($spMat);
  2.086 ms (515 allocations: 89.25 KiB)

julia> @btime eigs($sphermMat);
  2.149 ms (543 allocations: 90.34 KiB)
```

Having said that, however, you got me thinking. We could actually try to fully support complex bandstructures. My initial motivation is that degeneracy resolution relies on ordering of eigenvalues (to more quickly find the degeneracies themselves), but that is not necessary. I'll make some experiments.

**Comment by BacAmorim** [comment]
> Thanks for the feedback @BacAmorim! It's rather strange, for me the Hermitian overhead is minimal. I'm running both 1.3 and master, and Arpack is on version 0.4.0

I am using Julia v1.1.1 and Arpack is on v0.3.1. So maybe something must have improved in the mean time. I will try to update and see if the overhead of using `Hermitian` disappears. 

But does `eigs($sphermMat)`  still return complex eigenvalues?

**Comment by pablosanjose** [comment]
Yes, it's still complex (unless the matrix is real). At the moment I manually make eigenvalues real and sorted after the fact if the matrix is Hermitian.

**Comment by pablosanjose** [comment]
Hey @BacAmorim, check out #37 if you have a minute. I'd appreciate your thoughts on that.

**Comment by BacAmorim** [comment]
Just to provide some feedback: indeed in julia v1.3 the overhead of using `Hermitian` around a sparse matrix seems to be mostly gone. With julia v1.3 and Arpack v0.4 I now also get:

```julia
julia> @btime eigs($spMat);
      2.493 ms (431 allocations: 85.97 KiB)
julia> @btime eigs($sphermMat);
      2.548 ms (431 allocations: 85.97 KiB)
```

**Pull request merged**
